#!name=高德地图广告屏蔽
#!desc=屏蔽高德地图 App 各类广告，包括首页、导航、开屏、搜索、打车等
#!author=Vtous
#!homepage=https://github.com/Vtous

[Script]

# 高德地图广告拦截脚本（统一调用）
高德地图广告 = type=http-response, pattern=^https:\/\/m5(-zb)?\.amap\.com\/ws\/.*(splash_screen|card-service-plan-home|main-page|profile|marketingOperationStructured|tips_operation_location|hotword|nearbyrec_smart|routePlan|routeInfo|page\/main|content_info|resource|order_detail_car_tips|perception|plan|detail|coupon|recommend), requires-body=true, max-size=-1, script-path=https://raw.githubusercontent.com/Vtous/sure/refs/heads/master/amap-ad-block.js

[MITM]
hostname = m5.amap.com, m5-zb.amap.com
